version: "3"

services:
  webapp:
    build: .
    volumes:
      - .:/usr/src/app
    networks:
      - appnet
    restart: always
    depends_on:
      - nginx
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./frontend/static:/var/www/comengess/static
      - ./data:/var/www/comengess/data
    networks:
      - appnet
    restart: always

networks:
  appnet:
