version: "3"

services:
  webapp:
    build: .
    volumes:
      - .:/usr/src/app
    networks:
      - appnet
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80/tcp"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./frontend/static:/var/www/comengess/static
      - ./data:/var/www/comengess/data
    networks:
      - appnet

networks:
  appnet:
